name: ank_app
description: ank-app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #状态管理
  get: 4.6.6
  #http
  dio: 5.3.3
  #缓存
  shared_preferences: 2.2.2
  flutter_easyloading: 3.0.5
  intl: ^0.18.1
  retrofit: ^4.0.3
  cached_network_image: ^3.3.0
  collection: ^1.17.2
  talker_dio_logger: ^2.3.1
  easy_refresh: ^3.3.2+4
  fluttertoast: 8.2.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  gap: ^3.0.1
  font_awesome_flutter: ^10.6.0
  decimal: ^2.3.3
  auto_size_text: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.4
  pigeon: ^13.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/bottom_bar/
    - assets/images/common/
    - assets/images/
    - assets/images/platform/

flutter_assets_generator:
  output_filename: assets
  class_name: Assets
  output_dir: generated/
flutter_intl:
  enabled: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

