name: ank_app
description: ank-app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 3.0.4+316 #store
version: 3.5.0+357 #tf

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #状态管理
  get: 4.6.6
  #http
  dio: ^5.4.3+1
  #缓存
  shared_preferences: ^2.2.3
  flutter_easyloading: 3.0.5
  intl: ^0.18.1
  retrofit: ^4.1.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  talker_dio_logger: ^4.1.3
  easy_refresh: ^3.3.3+1
  fluttertoast: ^8.2.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
  gap: ^3.0.1
  font_awesome_flutter: ^10.7.0
  decimal: ^2.3.3
  auto_size_text: 3.0.0
  scrollable_positioned_list: 0.3.8
  expandable: 5.0.1
  flutter_inappwebview: ^6.0.0
  package_info_plus: ^7.0.0
  event_bus: ^2.0.0
  jpush_google_flutter: ^1.0.8
  flutter_fgbg: ^0.3.0
  #cell 侧滑按钮
  flutter_slidable: ^3.1.0
  lottie: ^3.1.0
  connectivity_plus: ^6.0.2
  #应用角标设置
  flutter_app_badger: ^1.5.0
  screenshot: ^2.3.0
  pointer_interceptor: ^0.10.1
  ff_native_screenshot: ^1.0.0
  share_plus: ^8.0.3
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.3
  equatable: ^2.0.5
  device_info_plus: ^10.1.0
  syncfusion_flutter_core: ^25.1.39
  syncfusion_flutter_datagrid: ^25.1.39
  expandable_text: ^2.3.0
  dart_scope_functions: ^0.1.6
  screenshot_callback:
    git:
      url: https://github.com/elliotkhd/flutter_screenshot_callback.git
      ref: d49ac805
  awesome_dio_interceptor: ^1.2.0
  flutter_native_splash: ^2.4.0
  screenshot_ntv: ^1.0.2
  extended_nested_scroll_view: ^6.2.1
  native_device_orientation: ^2.0.3
#  sentry_flutter: ^7.19.0


dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  retrofit_generator: ^8.1.0
  pigeon: ^18.0.0

#dependency_overrides:
#  package_info_plus: ^7.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/bottom_bar/
    - assets/images/common/
    - assets/images/
    - assets/images/orderflow/
    - assets/images/chart_left/
    - assets/images/setting/
    - assets/files/
    - assets/lottie/

flutter_assets_generator:
  output_filename: assets
  class_name: Assets
  output_dir: generated/
  filename_split_pattern: "[-_.]"
flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix:
flutter_intl:
  enabled: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

#dart pub global activate rps
scripts:
  gen: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch
  build:
    apk:
      flutter build apk --release --dart-define-from-file=evn_config/soto.json --obfuscate --split-debug-info=./symbols
    abb:
      flutter build appbundle --release --dart-define-from-file=evn_config/soto_play.json --obfuscate --split-debug-info=./symbols
    xcarchive:
      flutter build xcarchive --release --obfuscate --split-debug-info=./symbols
  locate:
    apk: open -R build/app/outputs/flutter-apk/app-release.apk
