name: ank_app
description: ank-app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 3.0.7+323 #store
version: 3.5.0+378 #tf

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #状态管理
  get: 4.6.6
  #http
  dio: ^5.5.0
  #缓存
  shared_preferences: ^2.3.0
  flutter_easyloading: 3.0.5
  intl: ^0.19.0
  retrofit: ^4.1.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  fluttertoast: ^8.2.6
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  gap: ^3.0.1
  font_awesome_flutter: ^10.7.0
  decimal: ^3.0.2
  auto_size_text: 3.0.0
  scrollable_positioned_list: 0.3.8
  expandable: 5.0.1
  flutter_inappwebview: ^6.0.0
  package_info_plus: ^8.0.1
  event_bus: ^2.0.0
  jpush_google_flutter: ^1.1.0
  #cell 侧滑按钮
  flutter_slidable: ^3.1.1
  lottie: ^3.1.2
  connectivity_plus: ^6.0.4
  #应用角标设置
  flutter_app_badger: ^1.5.0
  screenshot: ^3.0.0
  pointer_interceptor: ^0.10.1+1
  ff_native_screenshot: ^1.0.0
  share_plus: ^10.0.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.4
  equatable: ^2.0.5
  device_info_plus: ^10.1.1
  syncfusion_flutter_core: ^26.2.7
  syncfusion_flutter_datagrid: ^26.2.7
  syncfusion_flutter_charts: ^26.2.7
  expandable_text: ^2.3.0
  dart_scope_functions: ^0.1.8
  screenshot_callback:
    git:
      url: https://github.com/elliotkhd/flutter_screenshot_callback.git
      ref: d49ac805
  awesome_dio_interceptor: ^1.2.0
  flutter_native_splash: ^2.4.1
  screenshot_ntv: ^1.0.2
  extended_nested_scroll_view: ^6.2.1
  native_device_orientation: ^2.0.3
  k_chart: ^0.7.1
  visibility_detector: ^0.4.0+2
  infinite_scroll_pagination: ^4.0.0
  flutter_widget_from_html_core: ^0.15.1
  native_dio_adapter: ^1.3.0
#  interactive_chart: ^0.3.5
#  sentry_flutter: ^8.3.0
  flutter_cache_manager_dio: ^4.0.0


dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.2
  pigeon: ^21.1.0
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0
dependency_overrides:
  webview_flutter_android: 3.16.1
#dependency_overrides:
#  package_info_plus: ^7.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/bottom_bar/
    - assets/images/common/
    - assets/images/
    - assets/images/orderflow/
    - assets/images/chart_left/
    - assets/images/setting/
    - assets/files/
    - assets/lottie/

flutter_assets_generator:
  output_filename: assets
  class_name: Assets
  output_dir: generated/
  filename_split_pattern: "[-_.]"
flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix:
flutter_intl:
  enabled: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

#dart pub global activate rps
scripts:
  gen: dart pub run build_runner build --delete-conflicting-outputs
  watch: dart pub run build_runner watch
  build:
    apk:
      flutter build apk --release --dart-define-from-file=evn_config/soto.json --obfuscate --split-debug-info=./symbols
    aab:
      flutter build appbundle --release --dart-define-from-file=evn_config/soto_play.json --obfuscate --split-debug-info=./symbols
    xc:
      flutter build xcarchive --release --obfuscate --split-debug-info=./symbols
  locate:
    apk: open -R build/app/outputs/flutter-apk/app-release.apk
    aab: open -R build/app/outputs/bundle/release/app-release.aab
    xc: open -R build/ios/archive/Runner.xcarchive
  open:
    xc: open build/ios/archive/Runner.xcarchive
